---
abstract: 'Setup STDIN/STDOUT/STDERR With Proper Encodings'
author:
  - 'Copyright (c) 2008 Daisuke Maki C<< daisuke@endeworks.jp >>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.71'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Encode-StdIO
no_index:
  directory:
    - inc
    - t
recommends:
  Term::Encoding: 0
requires:
  perl: 5.8.0
version: 0.00001
